apiVersion: dp.wso2.com/v1alpha1
kind: Scope
metadata:
  labels:
    app.kubernetes.io/name: scope
    app.kubernetes.io/instance: scope-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: scope-sample
spec:
  # TODO(user): Add fields here
