apiVersion: dp.wso2.com/v1alpha1
kind: Authentication
metadata:
  labels:
    app.kubernetes.io/name: authentication
    app.kubernetes.io/instance: authentication-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: authentication-sample
spec:
  default:
    type: ext
    ext:
      serviceRef: 
        group: wso2/v1alpha2
        kind: Backend
        name: ext_authz-server
        port: 1234
      authTypes:
      - type: internalKey
        internalKey: 
          testConsoleHeaderName: Internal-Key