{{- if .Values.wso2.apk.dp.enabled }}

kind: Organization
apiVersion: cp.wso2.com/v1alpha1
metadata:
  name: {{ template "apk-helm.resource.prefix" . }}-default-organization
  namespace: {{ .Release.Namespace }}
spec:
  uuid: "a3b58ccf-6ecc-4557-b5bb-0a35cce38256"
  name: "default"
  displayName: "default"
  organizationClaimValue: "default"
  enabled: true
  serviceListingNamespaces:
    - "*"
{{- end -}}