# Copyright (c) 2022, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

{{- if .Values.wso2.apk.dp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.wso2.apk.dp.runtime.deployment.replicas }}
  strategy:
    type: {{ .Values.wso2.apk.dp.runtime.deployment.strategy }}
  selector:
    matchLabels:
{{ include "apk-helm.pod.selectorLabels" (dict "root" . "app" .Values.wso2.apk.dp.runtime.appName ) | indent 6}}
  template:
    metadata:
      labels:
        networkPolicyId: {{ .Values.wso2.apk.dp.runtime.deployment.npi }}
{{ include "apk-helm.pod.selectorLabels" (dict "root" . "app" .Values.wso2.apk.dp.runtime.appName ) | indent 8}}
    spec:
      serviceAccountName: {{ .Values.wso2.apk.auth.serviceAccountName }}
      containers:
        - name: runtime-ds
          image: {{ .Values.wso2.apk.dp.runtime.deployment.image }}
          imagePullPolicy: {{ .Values.wso2.apk.dp.runtime.deployment.imagePullPolicy }}
          ports:
            - containerPort: 9443
              protocol: "TCP"
{{ include "apk-helm.deployment.readinessProbe.http" .Values.wso2.apk.dp.runtime.deployment | indent 10 }}
{{ include "apk-helm.deployment.livenessProbe.http" .Values.wso2.apk.dp.runtime.deployment | indent 10 }}
{{ include "apk-helm.deployment.resources" .Values.wso2.apk.dp.runtime.deployment.resources | indent 10 }}
          volumeMounts:
            - mountPath: /home/wso2apk/runtime/security/wso2carbon.key
              name: runtime-signing-keystore-volume
              subPath: wso2carbon.key
            - mountPath: /home/wso2apk/runtime/security/mg.pem
              name: runtime-ds-jwt-validation-key-volume
              subPath: mg.pem
            - mountPath: /home/wso2apk/runtime/conf/Config.toml
              name: config-toml-volume
              subPath: Config.toml

      volumes:
        - name: runtime-signing-keystore-volume
          secret: 
            secretName: {{ template "apk-helm.resource.prefix" . }}-signing-keystore-secret
        - name: runtime-ds-jwt-validation-key-volume
          secret: 
            secretName: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-jwt-validaion-secret

        - name: config-toml-volume
          configMap:
            name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-configmap
        
{{- end -}}
