name: Release Adapter.
on:
  workflow_dispatch:
    inputs:
      release_version:
        required: true
        type: string
        description: "Release Version"
      next_version:
        type: string
        description: "Next Development Version"
  pull_request_target:
    types:
      - closed
      - opened
      - synchronize
    paths:
      - '**/adapter/**'
    branches:
      - 'main'
concurrency:
  group: adapter-${{ github.event.number }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Install Revive
        shell: sh
        run: |
          go install github.com/mgechev/revive@latest
      - name: Checkout apk-repo
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
          path: apk-repo
          token: ${{ secrets.WSO2_BOT_TOKEN }}
      - name: Set release username and email
        shell: sh
        run: |
          git config --global user.name ${{ secrets.WSO2_BOT_USER }}
          git config --global user.email ${{ secrets.WSO2_BOT_EMAIL }}
      - name: Run Release Gradle build
        if: github.event_name == 'workflow_dispatch'      
        run: |
          cd apk-repo/adapter
          ./gradlew release -Prelease.useAutomaticVersion=true -Pdocker_organization=${{ secrets.DOCKER_ORGANIZATION }} -Pdocker_username=${{ secrets.DOCKER_USERNAME }} -Pdocker_password=${{ secrets.DOCKER_PASSWORD }} -Prelease.releaseVersion=${{ github.event.inputs.release_version }} -Prelease.newVersion=${{ github.event.inputs.next_version }} -PmultiArch=true
      - name: Run Gradle Build
        run: |
          cd apk-repo/adapter
          ./gradlew build
      - name: Run Gradle Build
        if: github.event_name == 'pull_request_target' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          cd apk-repo/adapter
          ./gradlew docker_push -Pdocker_organization=${{ secrets.DOCKER_ORGANIZATION }} -Pdocker_username=${{ secrets.DOCKER_USERNAME }} -Pdocker_password=${{ secrets.DOCKER_PASSWORD }} -Pimage_version=latest -PmultiArch=true
          ./gradlew docker_push -Pdocker_organization=${{ secrets.DOCKER_ORGANIZATION }} -Pdocker_username=${{ secrets.DOCKER_USERNAME }} -Pdocker_password=${{ secrets.DOCKER_PASSWORD }} -Pimage_version=${{ github.sha }} -PmultiArch=true
      - name: run codecov
        uses: codecov/codecov-action@v3
        with:
          verbose: true # optional (default = false)
          directory: apk-repo/adapter
          flags: adapter          